apiVersion: v1
kind: ConfigMap
metadata:
  name: events-api-config
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: event-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "5432"
  DB_NAME: "ticketops"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"