apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata:
  name: db-credentials
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: ticketops-dev-secretmanager-db-host
    - secretKey: username
      remoteRef:
        key: ticketops-dev-db-username
    - secretKey: password
      remoteRef:
        key: ticketops-dev-db-password
  
--- 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: ticketops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: ticketops-dev-redis-host
    