apiVersion: v1
kind: Service
metadata:
  name: events-api-preview
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: events-api
  ports:
    - name: http 
      port: 80
      targetPort: 3000