apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: events-api
  namespace: ticketops
  labels:
    app: events-api
    version: v1.6.9
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
        version: v1.6.1
    spec:
      serviceAccountName: events-api-sa
      containers:
        - name: events-api
          image: "599476212737.dkr.ecr.ap-south-1.amazonaws.com/ticketops-dev-events-api:v1.17.0"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: events-api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: host
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
  strategy:
    blueGreen:
      activeService: events-api-service
      previewService: events-api-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
