apiVersion: v1
kind: ExternalSecret
metadata:
  name: bookings-worker-secret
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: db-credentials
    kind: ClusterSecretStore
  data:
    - secretKey: host
      remoteRef:
        key: ticketops-dev-secretmanager-db-host
    - secretKey: password
      remoteRef:
        key: ticketops-dev-db-password

--- 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookings-worker-redis-secrets
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  spec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretmanager
      kind: ClusterSecretStore
    target:
      name: db-credentials
      creationPolicy: Owner
    data: 
      - secretKey: host
        remoteRef:
          key: ticketops-dev-redis-host