apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-api-config
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: admin-api
spec:
  data:  
    NODE_ENV: "production"
    PORT: "4000"
    DB_PORT: "5432"
    DB_NAME: "ticketops"
    LOG_LEVEL: "info"
    ADMIN_EMAIL: "admin@ticketops.com"