apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-admin-secrets
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: admin-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: ticketops-dev-secretmanager-db-host
    - secretKey: db_password
      remoteRef:
        key: ticketops-dev-db-password
    - secretKey: db_username
      remoteRef: 
        key:  ticketops-dev-db-username
    - secretKey: redis
      remoteRef:
        key:  ticketops-dev-redis-host