apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: events-api-monitor
  namespace: ticketops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: event-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
