apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      values: | 
        clusterName: ticketops-dev-cluster
        serviceAccount:
          create: true 
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::599476212737:role/ticketops-dev-alb-controller
        region: ap-south-1
        vpcId: vpc-04c1eac91f6c5ad89
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true