apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: 
    argocd.argoproj.io/sync-wave: "2"
  spec:
    project: default
    source:
      repoURL: https://kubernetes.github.io/autoscaler
      targetRevision: 9.46.6
      chart: cluster-autoscaler
      helm: 
        values: |
          autoDiscovery:
            clusterName: ticketops-dev-cluster
          awsRegion: ap-south-1
          rbac:
            serviceAccount:
              name: cluster-autoscaler
              annotations:
                 eks.amazonaws.com/role-arn: arn:aws:iam::599476212737:role/ticketops-dev-cluster-autoscaler
              extraArgs:
                balance-similar-node-groups: true
                skip-node-with-system-pods: false
    destination:
      server: https://kubernetes.default.svc
      namespace: kube-system
    syncPolicy:
      automated:
        selfHeal: true
        prune: true