apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prerequisites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Suraj8853/ticketops-gitops
    targetRevision: HEAD
    path: manifests/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true