apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  type: ClusterIP
