apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-api-bindings
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: events-api-sa
    namespace: ticketops
roleRef:
  kind: Role
  name: events-api-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-api-binding
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: admin-api-sa
    namespace: ticketops
roleRef:
  kind: Role
  name: admin-api-role
  apiGroup: rbac.authorization.k8s.io 

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookings-worker-binding
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
subjects:
  - kind: ServiceAccount
    name: bookings-worker-sa
    namespace: ticketops
roleRef:
  kind: Role
  name: bookings-worker-role
  apiGroup: rbac.authorization.k8s.io 

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-binding
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: dashboard-sa
    namespace: ticketops
roleRef:
  kind: Role
  name: dashboard-role
  apiGroup: rbac.authorization.k8s.io
