apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: events-api-role
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["db-credentials","redis-credentials"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["events-api-config"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-api-role
  namespace: ticketops
  annotations:
     argocd.argoproj.io/sync-wave: "1"
rules: 
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["admin-api-secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["admin-api-config"]
    verbs: ["get"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookings-worker-role
  namespace: ticketops
  annotations:
     argocd.argoproj.io/sync-wave: "1"
rules:
 - apiGroups: [""]
   resources: ["secrets"]
   resourceNames: ["db-credentials","redis-credentials"]
   verbs: ["get"]
 - apiGroups: [""]
   resources: ["configmaps"]
   resourceNames: ["bookings-worker-config"]
   verbs: ["get"]


--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dashboard-role
  namespace: ticketops
  annotations:
     argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["dashboard-config"]
    verbs: ["get"]

