apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-api-sa
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "1"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-api-sa
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "1"


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookings-worker-sa
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: ticketops
  annotations:
    argocd.argoproj.io/sync-wave: "1"